### ISSUE TITLE
[Bug]: Does not affect ores from Create

### ISSUE THREAD

**Issue by Qazerowl** [someaddons/caveore#4]
### Describe the bug you're experiencing

When the config is set to air chance 100%, I am able to verify using an xray mod that (almost) all iron ore that is not part of a cave wall is removed. But the zinc ore from the Create mod is not changed: most of it is spawning buried in stone. Also, ores from the Mining Master mod are unchanged. I have also tried setting the blacklist to a whitelist and including "create:zinc_ore", this does not do anything either.

The zinc ore is added to the forge:ores tag.

### Reproducability

set air chance to 100%, generate a new world with the create mod, check for zinc in the walls using xray.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

na

**Comment by someaddons** [comment]
ye the mod can only affect ores which are using vanilla's ore config features properly
