### ISSUE TITLE
[Bug]: Config file not changing world generation

### ISSUE THREAD

**Issue by iPauloLopes** [someaddons/caveore#5]
### Describe the bug you're experiencing

I'm trying to make ores really rare so I changed "spawnchance" to 10 and "hiddenOreChance" to 1 but when a new world is generated there are still a lot of ores underground. I thought Terralith was causing the issue but even after disable it the ores keep generating.

I'm using a xray texture pack + nightvision effect + spectator mode to see all ores around.
Fabric 1.20.1 - 3.5 (can't select 1.20 in the Minecraft version box)

### Reproducability

Install the mod and generate a new world. Use xray + nightvision + spectator and take a walk underground.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/iPauloLopes/2799aca0a42093d3c58506b50161dd2a

**Comment by someaddons** [comment]
Fixed in 3.7, hidden ore chance config did not apply
